### ISSUE TITLE
health indicators for states returns no variables

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#33]
see: /region/0400000US53/Washington/health_indicators/health.health_indicators.data_value/2011?

and attached image of API results. Should align w/ prod. Actual data set looks like a snowflake: 

https://odn.data.socrata.com/resource/ph2b-gm84

I think we actually want to rollup in the UI a number of the variables currently under the "Health Behaviors" data set in addition to whats on prod - see things like HIV prevalence rate.

![screen shot 2016-08-24 at 11 43 59 am](https://cloud.githubusercontent.com/assets/1051776/17943440/429e31f6-69f0-11e6-83b1-91d39e85f5a7.png)

**Comment by aaasen** [comment]
This is similar to #34. There is only one variable in the health indicators dataset, and that is `data_value`. However, there are multiple constraints: 

```
constraints: [
  "year",
  "question",
  "question_response",
  "break_out"
]
```

We should have a drop down menu to select a value for each constraint. For example, 

```
year=2013
question=Have you ever been told by a doctor that you have diabetes?
question_response=Yes
break_out=Overall
```

To implement this, we first make a call to `/data/availability` to get the constraints available. Frontend can display the constraints in whatever order. Then, call `/data/constraint` to get all of the possible values for each constraint. If necessary I can make a demo to show how it would work.

Closing since this is not a problem with the backend.
