### ISSUE TITLE
occupations data not aligning w/ prod

### ISSUE THREAD

**Issue by zang0** [socrata/odn-backend#34]
http://opendatanetwork-staging.herokuapp.com/region/0400000US53/Washington/occupations/jobs.occupations.employed_rank/2013?

vs

http://www.opendatanetwork.com/region/0400000US53/Washington/occupations/business_and_finance/2013?

note: tier 3 cat menu not the same - API not returning the same values as prod

![screen shot 2016-08-24 at 12 01 29 pm](https://cloud.githubusercontent.com/assets/1051776/17943973/889b7784-69f2-11e6-9ce9-5ed56b6d60b0.png)
![screen shot 2016-08-24 at 12 01 20 pm](https://cloud.githubusercontent.com/assets/1051776/17943972/88918cf6-69f2-11e6-88f7-c90fca59327a.png)

**Comment by aaasen** [comment]
This is the same as the problem with cost of living and other datasets with multiple constraints. To solve this we should add a drop down menu for each constraint of the dataset instead of just year. For example, the occupations dataset would have menus to select the variable (number employed, percent employed, etc.), occupation (business and finance, computers and math, etc.) and year.

Closing since in this case the backend is doing the right thing and the frontend will need to change.
